name: flutter_web_bluetooth
description: A library to use the web bluetooth api.
version: 0.0.2
homepage: https://github.com/jeroen1602/flutter_web_bluetooth/
repository: https://github.com/jeroen1602/flutter_web_bluetooth/
issue_tracker: https://github.com/jeroen1602/flutter_web_bluetooth/issues/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: '>=0.6.3 <0.7.0'
  rxdart: '>=0.26.0 <0.28.0'

dev_dependencies:
  test: ^1.17.4
